name: Reusable Workflow Example

on:
  push:
    paths:
    - '.github/workflows/reuse.yml'
  workflow_dispatch:
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: echo setup

  build-deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Resuse
      uses: ./.github/workflows/reusable-workflow.yml
